export const opdArr1 = [
  "Inj. TT",
  "Inj. Voveran",
  "Inj. Contramal",
  "X-Ray",
  "Check X-Ray",
  "ASD",
  "Stitching",
  "CLW Repaired",
  "Splintage",
  "WD & WT",
  "K wire",
  "POP Slab",
  "ASD",
  "Stitching",
  "Splintage",
  "CLW Repaired",
  "WD & WT",
  "K wire",
  "POP Slab",
];
export const opdArr2 = [
  "Hard bed/ no pillow",
  "Q.C. Exercises",
  "Sponge under heel",
  "Zopel DSR",
  "Meftal Forte",
  "Zacy",
  "Prosulide AS",
  "Dol SP",
  "Enbidase-AP",
  "Refzil-O",
  "Cifran",
  "Rapicef CV",
  "Cefakind-CV",
  "Cefuroxime",
  "Cefadroxyl",
  "Farobact",
  "Linezolid",
  "Lizokef",
  "Accotac-PS",
];
