export const opdArr1 = [
  { value: "Inj. TT", id: 0 },
  { value: "Inj. Contramal", id: 1 },
  { value: "Inj. Voveran", id: 2 },
  { value: "X-Ray", id: 3 },
  { value: "Check X-Ray", id: 4 },
  { value: "ASD", id: 5 },
  { value: "Stitching", id: 6 },
  { value: "CLW Repaired", id: 7 },
  { value: "Splintage", id: 8 },
  { value: "WD & WT", id: 9 },
  { value: "K wire", id: 10 },
  { value: "POP Slab", id: 11 },
  { value: "ASD", id: 12 },
  { value: "Stitching", id: 13 },
  { value: "Splintage", id: 14 },
  { value: "CLW Repaired", id: 15 },
  { value: "WD & WT", id: 16 },
  { value: "K wire", id: 17 },
  { value: "POP Slab", id: 18 },
];
export const opdArr2 = [
  { value: "Hard bed/ no pillow", id: 1 },
  { value: "Q.C. Exercises", id: 2 },
  { value: "Sponge under heel", id: 3 },
  { value: "Zopel DSR", id: 4 },
  { value: "Meftal Forte", id: 5 },
  { value: "Zacy", id: 6 },
  { value: "Prosulide AS", id: 7 },
  { value: "Dol SP", id: 8 },
  { value: "Enbidase-AP", id: 9 },
  { value: "Refzil-O", id: 10 },
  { value: "Cifran", id: 11 },
  { value: "Rapicef CV", id: 12 },
  { value: "Cefakind-CV", id: 13 },
  { value: "Cefuroxime", id: 14 },
  { value: "Cefadroxyl", id: 15 },
  { value: "Farobact", id: 16 },
  { value: "Linezolid", id: 17 },
  { value: "Lizokef", id: 18 },
  { value: "Accotac-PS", id: 19 },
];
